### ISSUE TITLE
[BUG] Doesn't work properly with AutoHud

### ISSUE THREAD

**Issue by Zorklis** [SuperPro148/ArmorHUD#1]
Using 1.19.2.
Problem:
When the Hud goes down due to AutoHud, the armor set goes down and doesn't dissapear but goes out of the armor hud/boxes.

**Comment by kyh148** [comment]
sorry that i didn't notice your issue earlier, i'll look into it tomorrow

**Comment by kyh148** [comment]
After looking into it for a while and trying to figure out a way to make it compatible, I couldn't find anything that works, sorry.

It seems to be due to the fact that I am essentially rendering hotbar items, AutoHud has a mixin for that method to move the items down.
